# Generated by Django 3.1.4 on 2020-12-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20201205_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='img'),
        ),
    ]
